### ISSUE TITLE
Caching is on, even if you pass in 0 ttl

### ISSUE THREAD

**Issue by zandzpider** [MaartenStaa/laravel-41-route-caching#12]
``` php
<?php
Route::cache(__FILE__, function() {

// do stuff
}, 0);
```

**Comment by zandzpider** [comment]
the problem i'm having with the route cache is that i include subroutes in my routes.php.
when i change my subroutes, the filemodified time does not get changed on routes.php (ofcourse).

This is why i would like a simple way to always have the route cache on. but pass in a (do not cache) when i'm not in production.

if that made any sense?

**Comment by MaartenStaa** [comment]
In such a case, just group the routes in each individual route file in a `Route::cache` call, and make sure to include those outside of a `Route::cache` call. Does that help?
