### ISSUE TITLE
Throws error on my app which is built on laravel 4.2.17

### ISSUE THREAD

**Issue by manik005** [MaartenStaa/laravel-41-route-caching#14]
I added the package and also included the service provider but it throws the following error. 

```
Call to undefined method Illuminate\Routing\Router::cache()
```

Am I doing anything wrong or Any idea on why this is occurring ?

**Comment by MaartenStaa** [comment]
Hey @manik005, sorry for the delay in replying. Can you check whether you added the package's service provider _after_ Laravel's RoutingServiceProvider please?

Based on the error message, it sounds like Laravel's is being processed after the one from this package, which makes it go back to using the default Router class instead of mine.

**Comment by manik005** [comment]
Hi @MaartenStaa , no problem. Yeah I have added your package's service provider _after_ Laravel's Routing Service Provider but still getting the same error. Also I have tried `MaartenStaa\Routing\Route::Cache` in the routes.php file but gott this error `Call to undefined method MaartenStaa\Routing\Route::cache()`

Yes, Looks like that's the problem but `m not sure why this is not working as expected. 

Thanks

**Comment by MaartenStaa** [comment]
@manik005 I'm also running Laravel 4.2.17 and don't have any problems. Would you mind putting a copy of your app.php config file on a Github gist somewhere so I can use that to figure out what's wrong?

Of course make sure to remove any sensitive information such as encryption key, URL, ...

**Comment by manik005** [comment]
@MaartenStaa  Here is the gist https://gist.github.com/manik005/4729b492c7c90c3817a4 containing my app.php

**Comment by MaartenStaa** [comment]
@manik005 Looks alright so far. And just to make sure, in your routes.php file you're just using the standard `Route::` facade?

**Comment by manik005** [comment]
yeah bud.. `m just using `Route::` facade, that's why I can't figure out what is going wrong.

**Comment by manik005** [comment]
yeah bud.. 'm just using `Route::` facade, that's why I can't figure out what is going wrong.

**Comment by manik005** [comment]
Hey @MaartenStaa  I think I have figured it out.. It was actually due to `Jlapp\Swaggervel\SwaggervelServiceProvider`. It was including `route.php` in its service provider which was before `MaartenStaa\Routing\RoutingServiceProvider`.  So I just swapped their order and it worked :smile:  Thanks for the support :+1:
