### ISSUE TITLE
Clean cache

### ISSUE THREAD

**Issue by pfbernardo** [MaartenStaa/laravel-41-route-caching#15]
Hi,

Thanks for the great library. It is very useful in projects with laravel 4.2

This is more a request, not a bug.

Is it possible for you to create a public function in the Router.php to clean the cache?
Sometimes we don't change the Routes.php but if we add a method in a controller that is defined by Route::Controller it will give 404. This happens when routes are cached and it didn't had that method before.
If I had that method (could be called though the Facade like Route::cleanCache() ) I could make a command that calls it.

Thanks,
Pedro

PS. sorry about the bad english

**Comment by MaartenStaa** [comment]
Hi Pedro,

Thanks for the praise!

Great idea. I published version 1.0.3 that implements this. And your English is fine, don't worry about it!

**Comment by pfbernardo** [comment]
Hi Maarten,

Thanks so much for this.

Cheers,
Pedro
