### ISSUE TITLE
Incompatible with older 4.1.* versions

### ISSUE THREAD

**Issue by MaartenStaa** [MaartenStaa/laravel-41-route-caching#3]
As pointed our by @yuripave in pull request #2, integration tests with Laravel < 4.1.19 fail. I should check each individual version and figure out if I can make it work without getting too hacky.

Otherwise, may need to restrict Laravel version number (as updating from 4.1.x where x < 19 to 4.1.y with y >= 19 shouldn't be a problem in almost all cases).

**Comment by yuripave** [comment]
@MaartenStaa :+1:! Also I tried to integrate the package with my project today. Note that the composer hyphen version constraints is [recently added](https://github.com/composer/composer/commit/ebab9db27ac3887babc8404107dd448d974b2f43), which means that for those that were only using tagged releases of composer (latest is 1.0.0-alpha9) or didn't do self-update often cannot install the package and will get this error: `[UnexpectedValueException] Could not parse version constraint`. Doing a self-update and update to latest master works fine. Maybe you can consider to use the range version constraint.

**Comment by MaartenStaa** [comment]
I see. I created issue #4 for that.

If you run into anything else, feel free to create a new issue! I've used the code from this package in production for more than a year, but that's just a single configuration, so it would be surprising if nothing else popped up.

**Comment by yuripave** [comment]
Will do, thanks so much! The package works solid for me so far.
